---
- name: Execute task. (build_Environment.yml)
  import_tasks: build_Environment.yml
  vars:
    environment_level: machine
    environment_target: "{{ VAR_WIN_EnvSetting.Machine }}"
  when: VAR_WIN_EnvSetting.Machine is defined
